[package]
name = "raffl-macro"
description = "Rust Asynchronous FFI Library - A library for writing asynchronous callback-friendly FFI"
version = "0.1.1"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
proc-macro-error = "1.0.4"
quote = "1.0.26"
syn = { version = "2.0.15", features = ["full"] }
anyhow = "1.0.70"

[dev-dependencies]
anyhow = "1.0.70"
trybuild = "1.0.80"
